export const ADD_TODO = 'add_todo'
export const DELETE_TODO = 'delete_todo'
export const TOGGLE_TODO = 'toggle_todo'
export const DELETE_ALL = 'delete_allTodos'
export const SET_FILTER = 'set_filter'
export const TOGGLE_THEME = 'toggle_theme'
